# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import firstApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20210117_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.CharField(default=firstApp.models.Username.create_id, editable=False, max_length=1000, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('year', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
