# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-19 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_auto_20210119_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='year',
        ),
    ]
