# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_remove_username_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=499),
        ),
    ]
