# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-01-19 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0006_auto_20210119_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2021, 1, 19, 18, 30, 40, 792594, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='firstApp.Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
